/**
 * app/legal/[doc].tsx
 *
 * In-app legal document viewer: /legal/terms, /legal/privacy,
 * /legal/safety-pledge. Text comes from constants/legalDocs.ts, which is
 * generated byte-identical from the legal/ markdown (the legal source of
 * truth, 2A-f) and drift-guarded by legalDocs.test.ts.
 *
 * Renders a pragmatic markdown subset: headings, bullets, paragraphs.
 * HTML comments (adviser notes) are stripped from display.
 */

import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { Colors, Typography, Spacing } from '../../constants/theme';
import { LEGAL_DOCS } from '../../constants/legalDocs';

interface Block {
  type: 'h1' | 'h2' | 'h3' | 'bullet' | 'para' | 'rule';
  text: string;
}

/** Markdown-lite → typed blocks. Inline emphasis/comments are stripped. */
export function parseMarkdown(markdown: string): Block[] {
  const cleaned = markdown.replace(/<!--[\s\S]*?-->/g, '');
  const blocks: Block[] = [];
  let paragraph: string[] = [];

  const flush = () => {
    const text = paragraph.join(' ').trim();
    if (text) blocks.push({ type: 'para', text });
    paragraph = [];
  };

  for (const raw of cleaned.split('\n')) {
    const line = raw.trimEnd();
    const stripped = line.replace(/\*\*/g, '').replace(/^>\s?/, '').trim();
    if (!stripped) { flush(); continue; }
    if (/^---+$/.test(stripped)) { flush(); blocks.push({ type: 'rule', text: '' }); continue; }
    if (stripped.startsWith('### ')) { flush(); blocks.push({ type: 'h3', text: stripped.slice(4) }); continue; }
    if (stripped.startsWith('## ')) { flush(); blocks.push({ type: 'h2', text: stripped.slice(3) }); continue; }
    if (stripped.startsWith('# ')) { flush(); blocks.push({ type: 'h1', text: stripped.slice(2) }); continue; }
    if (/^[-*] /.test(stripped)) { flush(); blocks.push({ type: 'bullet', text: stripped.slice(2) }); continue; }
    paragraph.push(stripped);
  }
  flush();
  return blocks;
}

export default function LegalDocScreen(): React.ReactElement {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { doc } = useLocalSearchParams<{ doc: string }>();
  const legalDoc = doc ? LEGAL_DOCS[doc] : undefined;

  return (
    <View style={[styles.screen, { paddingTop: insets.top + Spacing.lg }]} testID="legal-doc-screen">
      <View style={styles.headerRow}>
        <TouchableOpacity
          onPress={() => router.back()}
          accessibilityRole="button"
          accessibilityLabel="Go back"
          testID="back-button"
          hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
        >
          <Ionicons name="chevron-back" size={24} color={Colors.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.screenTitle} numberOfLines={1}>{legalDoc?.title ?? 'Legal'}</Text>
        <View style={{ width: 24 }} />
      </View>

      {!legalDoc ? (
        <View style={styles.center} testID="legal-not-found">
          <Text style={styles.para}>Document not found.</Text>
        </View>
      ) : (
        <ScrollView contentContainerStyle={styles.content} testID={`legal-${legalDoc.slug}`}>
          {parseMarkdown(legalDoc.markdown).map((block, i) => {
            switch (block.type) {
              case 'h1': return <Text key={i} style={styles.h1}>{block.text}</Text>;
              case 'h2': return <Text key={i} style={styles.h2}>{block.text}</Text>;
              case 'h3': return <Text key={i} style={styles.h3}>{block.text}</Text>;
              case 'rule': return <View key={i} style={styles.rule} />;
              case 'bullet': return (
                <View key={i} style={styles.bulletRow}>
                  <Text style={styles.bulletDot}>•</Text>
                  <Text style={styles.para}>{block.text}</Text>
                </View>
              );
              default: return <Text key={i} style={styles.para}>{block.text}</Text>;
            }
          })}
        </ScrollView>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  // paddingTop is set inline (insets.top + Spacing.lg) so the title clears the status bar/Dynamic Island on every device instead of a fixed value.
  screen: { flex: 1, backgroundColor: Colors.background },
  headerRow: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: Spacing.screenPadding, marginBottom: Spacing.md,
  },
  screenTitle: { ...Typography.headingLarge, color: Colors.textPrimary, flex: 1, textAlign: 'center' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  content: { paddingHorizontal: Spacing.screenPadding, paddingBottom: Spacing.xxxxxl, gap: Spacing.sm },
  h1: { ...Typography.headingLarge, color: Colors.textPrimary, marginTop: Spacing.md },
  h2: { ...Typography.headingMedium, color: Colors.textPrimary, marginTop: Spacing.md },
  h3: { ...Typography.headingSmall, color: Colors.textPrimary, marginTop: Spacing.sm },
  para: { ...Typography.bodySmall, color: Colors.textSecondary, flex: 1 },
  bulletRow: { flexDirection: 'row', gap: Spacing.sm, paddingLeft: Spacing.sm },
  bulletDot: { ...Typography.bodySmall, color: Colors.textSecondary },
  rule: { height: 1, backgroundColor: Colors.border, marginVertical: Spacing.sm },
});
